# Generated by Django 2.2.2 on 2019-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0003_auto_20190614_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
