# Generated by Django 2.2.2 on 2019-06-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0005_auto_20190614_0927'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
    ]
